<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>name</key>
        <string>Kuki</string>
        <key>scopeName</key>
        <string>main</string>
        <key>fileTypes</key>
        <array>
            <string>kuki</string>
        </array>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>keyword.control.kuki</string>
                <key>match</key>
                <string>\b(INGREDIENTS|UTENSILS|STEPS)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.letter.kuki</string>
                <key>match</key>
                <string>\b(the|into|in|to|for|and)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>entity.name.function.kuki</string>
                <key>match</key>
                <string>\b(Mix|Cut|Place|Heat|Bake)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.numeric.kuki</string>
                <key>match</key>
                <string>\b(\d+(\.\d+)?|seconds|minutes|hours|degrees|Farenheit|g|ml)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>punctuation.kuki</string>
                <key>match</key>
                <string>(:|-|\.)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.other.kuki</string>
                <key>match</key>
                <string>\b([a-zA-Z]+)\b</string>
            </dict>
        </array>
    </dict>
</plist>
